const areas = {"cloudComputing": "Cloud Computing and/or Distributed systems",
              		"operatingSystems": "Operating systems",
              		"networks": "Computer networks",
              		"algorithms": "Algorithms",
              		"humanComputerInteraction": "Human-Computer Interaction",
              		"programmingLanguages": "Programming Languages",
              		"naturalLanguageProcessing": "Natural Language Processing",
              		"machineLearning": "Machine Learning and/or Artificial Intelligence",
              		"robotics": "Robotics",
              		"graphics": "Graphics",
              		"security": "Security",
              		"optimization": "Optimization",
              		"computationalBiology": "Computational Biology",
              		"other": "Other"};
