name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: NPM Install
        run: npm install
      - name: Lint
        run: npm run lint || echo "Suppress failure for now"
      - name: Build
        run: npm run build
